### ISSUE TITLE
Browser step to make it work

### ISSUE THREAD

**Issue by jcc2303** [marko-js-samples/marko-hot-reload#2]
Hi!

I was trying to add browser hot reload unsuccessfully, marko is able to see whats is happening, but the browser(chrome) is not reloaded. I was follow the step that you write, but  am I missing some extra step?

could you help me, thanks in advance.

my terminal output:
$ browser-refresh server.js
[browser-refresh] Watching: /home/javiercabrera/examples-workspace/marko-hot-reload
[browser-refresh] Ignore rule: *.marko.js
[browser-refresh] Ignore rule: /node_modules
[browser-refresh] Ignore rule: npm-debug.log
[browser-refresh] App started (pid: 1664)
Server started on port 8000
[browser-refresh] Waited 1500ms without receiving "online" from child process. Page refresh triggered over WebSockets connection.
[browser-refresh] Triggering refresh of client pages...
[browser-refresh] Refresh triggered
flush is deprecated. Use flushHeaders instead.
Marko template modified:  /home/javiercabrera/examples-workspace/marko-hot-reload/views/index.marko
[marko/hot-reload] File modified: /home/javiercabrera/examples-workspace/marko-hot-reload/views/index.marko
Marko template modified:  /home/javiercabrera/examples-workspace/marko-hot-reload/views/index.marko
[marko/hot-reload] File modified: /home/javiercabrera/examples-workspace/marko-hot-reload/views/index.marko
[browser-refresh] File has been changed: views/index.marko
[browser-refresh] Restarting app...
[browser-refresh] App started (pid: 2040)
Server started on port 8000
[browser-refresh] Waited 1500ms without receiving "online" from child process. Page refresh triggered over WebSockets connection.
[browser-refresh] Triggering refresh of client pages...
[browser-refresh] Refresh triggered

**Comment by patrick-steele-idem** [comment]
Hi @jcc2303, I have updated the README.md to move more of the documentation from the `browser-refresh` module into this modules documentation. I think you were missing the following:

In your main page template:

``` xml
<!doctype html>
<html>
    <head>
        ...
    </head>
    <body>
        ...

        <browser-refresh enabled="true" />
    </body>
</html>
```

In your main server script:

``` javascript
app.listen(port, function() {
    console.log('Listening on port %d', port);

    if (process.send) {
        process.send('online');
    }
});
```

Please let me know if that doesn't solve your problem.
