### ISSUE TITLE
Reload kinda works, but route still displays old template render

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js-samples/marko-hot-reload#3]
What is wrong with this? I've switched to using chokidar as per your recommendation. It detects the file modification and compiles a new `.js` file, but reload of the page changes nothing.
Is it a caching issue!?

``` js
'use strict';
let marko = require('marko');
var path = require('path');
var chokidar = require('chokidar');
var refresher = require('marko/browser-refresh');
var reloader = require('marko/hot-reload');

function watchViews(viewsDir) {
  let ignorePattern = /[\/\\]\./;
  // ignored: ignorePattern
  let watchOptions = {persistent: true, ignore: ignorePattern};
  // watcher
  //   .on('add', function(path) { log('File', path, 'has been added'); })
  //   .on('change', function(path) { log('File', path, 'has been changed'); })

  function fileChangeHandler(filePath, stats) {
    stats = stats || {};
    if (/\.marko$/.test(filePath)) {
      var time = stats.mtime || new Date();
      console.log('Marko file change detected:' + time);
      // Resolve the filename to a full template path:
      var templatePath = filePath;
      console.log('Marko template modified: ', templatePath);
      // Pass along the *full* template path to marko
      reloader.enable();
      reloader.handleFileModified(templatePath);
    }
  }

  // One-liner for current directory, ignores .dotfiles
  var watcher = chokidar.watch(viewsDir, watchOptions);
  watcher.on('change', fileChangeHandler);
}
```

As you can see, it detects that I change the `.marko` file. 

Hot reload logs this message `[marko/hot-reload] File modified: /Users/kristianmandrup/repos/markoa/markoa-tester/apps/index/page/index.marko` 

Which is exactly the path to the template I modified.

And indeed it has compiled the `.marko` file into a new `index.marko.js` file

But when I reload the browser, I still get my old page...

``` sh
13:42 $ node test/
Missing static: in options for static mw
Added static dir:public
Added static dir:dist
Added static dir:semantic/dist
create route index
global state: {}
route / : index
Watching: .marko templates in /Users/kristianmandrup/repos/markoa/markoa-tester/apps/index/page for hot reload!!
Marko appplication ready on port 4005
page state {}
template data {}
rendering template: /Users/kristianmandrup/repos/markoa/markoa-tester/apps/index/page/index.marko
state: { '$global': {} }
Marko file change detected:Tue Aug 11 2015 13:43:08 GMT+0100 (BST)
Marko template modified:  /Users/kristianmandrup/repos/markoa/markoa-tester/apps/index/page/index.marko
[marko/hot-reload] File modified: /Users/kristianmandrup/repos/markoa/markoa-tester/apps/index/page/index.marko
page state {}
template data {}
rendering template: /Users/kristianmandrup/repos/markoa/markoa-tester/apps/index/page/index.marko
state: { '$global': {} }
```

**Comment by patrick-steele-idem** [comment]
Hi @kristianmandrup,  you need to include `require('marko/hot-reload').enable()` or `require('marko/browser-refresh').enable()` _before_ any of your templates are loaded  (ideally at the very beginning of your main script). The hot reload functionality for Marko works by monkey-patching loaded templates to enable hot reloading. If you don't enable hot reloading before the template is loaded then it won't be able to be hot reloaded. Here's where the magic happens in case it is helpful:

https://github.com/marko-js/marko/blob/293f891c528719310aca9b776096ca3a059d37a3/hot-reload/index.js#L27-L76

Let me know if you still have questions.

**Comment by kristianmandrup** [comment]
Thanks :) I already discovered that when I was playing around and debugging... but I'm sure this is useful for someone else going down the same "rabbit hole"!!!

**Comment by Globik** [comment]
I am also on chokidar and marko. But the template wan't be reloaded. Should I catch with choki an event onchange? But what's next? I am on windows 7 btw
Should hot reload enable stand before node-require.install() or after?

**Comment by Globik** [comment]
I have chokidar removed. Using native fs.watch. It getting to work. Reload now is ok.
Perhaps I don't understand properly how should chokidar work. Keine Idee.

**Comment by patrick-steele-idem** [comment]
@Globik Make sure that the template path passed to `reloader.handleFileModified(templatePath)` is the fully resolved file system path. If you are still seeing issues it might be helpful if you open another issue and share some code that is not working for you.

**Comment by Globik** [comment]
@patrick-steele-idem  it is work now. With fs.watch.
